# Generated by Django 6.0.5 on 2026-05-29 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='clothes/', verbose_name='图片')),
                ('clothes_name', models.CharField(max_length=100, verbose_name='衣服名称')),
                ('category', models.CharField(choices=[('top', '上衣'), ('bottom', '下装'), ('outerwear', '外套'), ('dress', '连衣裙'), ('shoes', '鞋子'), ('accessory', '配饰')], max_length=20, verbose_name='类别')),
                ('color', models.CharField(max_length=100, verbose_name='颜色')),
                ('style_label', models.CharField(max_length=100, verbose_name='风格标签')),
                ('thickness', models.CharField(choices=[('thin', '薄'), ('medium', '中'), ('thick', '厚')], max_length=100, verbose_name='厚度')),
                ('temp_min', models.IntegerField(verbose_name='最低温度')),
                ('temp_max', models.IntegerField(verbose_name='最高温度')),
                ('weather', models.CharField(max_length=100, verbose_name='适合天气')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名字')),
            ],
        ),
    ]
