# Generated by Django 6.0.5 on 2026-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(blank=True, choices=[('top', '上衣'), ('bottom', '下装'), ('outerwear', '外套'), ('dress', '连衣裙'), ('shoes', '鞋子'), ('accessory', '配饰')], default='top', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='clothes_name',
            field=models.CharField(blank=True, default='未命名', max_length=100, verbose_name='衣服名称'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(blank=True, default='未知', max_length=100, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='风格标签'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='temp_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='最高温度'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='temp_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='最低温度'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='thickness',
            field=models.CharField(blank=True, choices=[('thin', '薄'), ('medium', '中'), ('thick', '厚')], default='medium', max_length=100, verbose_name='厚度'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='weather',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='适合天气'),
        ),
    ]
